type ErrorTypes = {
  UNKNOWN_ERROR: 1;
  PRODUCT_MISSING_PROPERTIES: 2;
  PRODUCT_ALREADY_EXISTS: 3;
  AUTHORIZATION_DENIED: 4;
};

const EErrors: ErrorTypes = {
  UNKNOWN_ERROR: 1,
  PRODUCT_MISSING_PROPERTIES: 2,
  PRODUCT_ALREADY_EXISTS: 3,
  AUTHORIZATION_DENIED: 4,
} as const;
export default EErrors;